### ISSUE TITLE
"イシューベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by masuda456** [masuda456/runteq_graduate#13]
■ 機能

 1. ユーザー管理機能
  - 性別、アカウント情報、おおまかなレベル(ベンチプレス、デッドリフト、スクワットの重量など)、  
    非表示設定(一旦は同性のみかどうかのみ実装)などを登録しマッチングやログイン認証に利用します。

 2. ログイン認証機能
 
 3. ワークアウト予定の登録機能
  - ジムの名前や住所を入れると付近の地図が表示される、任意のジムや行うトレーニングを選択します。
 
 4. ワークアウト予定の検索機能
  - ジムの名前や住所を入れると付近の地図が表示される、ワークアウト予定が表示されます。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
READMEに記載されている

- 声をかけられてもいいですよ登録をする機能
- 一緒にトレーニングをやってくれる人を探す機能

上記のカードが見受けられなかったので、追加をお願いします。

---

またデプロイ、rails newなどのカードも作成しましょう。

・外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5〜を付けているように見受けられました。ストーリーポイント1,2,3になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by masuda456** [comment]
ご確認・ご指摘ありがとう御座います。
下記のように対応いたしましたので各issueのご確認お願い致します。 
  
 

> ・声をかけられてもいいですよ登録をする機能
> ・一緒にトレーニングをやってくれる人を探す機能

失礼致しました。
名称が変な感じがしたので、変更しておりました。
issueの()内に元々の機能名を記載しておきました。

> またデプロイ、rails newなどのカードも作成しましょう。

rails newは環境構築(開発)、デプロイはリリース作業と環境構築(本番)にて担っているように作成してみました。

> 外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

GooglemapApi調査のカードを３種類作成しました。

> また、ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5〜を付けているように見受けられました。ストーリーポイント1,2,3になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

ご指摘事項対応いたしました。
テストが何回やることになるのか分からなかったので一旦、
修正と２回目テストと言うカードを新たに作成して対応致しました。


よろしくお願い致します。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
LGTMです！
