### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by masuda456** [masuda456/runteq_graduate#23]
## 各種情報
サービス名：OK 合トレ
サービスURL：https://runteq-graduate-72b5a7766d87.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] ユーザー管理機能
サインアップやプロフィール設定などの画面が相当します
- [x] ログイン認証機能
サインイン画面が相当します
- [x] 声をかけられてもいいですよ登録をする機能
/mainでワークアウトの予定を登録をクリック
- [x] 一緒にトレーニングをやってくれる人を探す機能
/mainでワークアウトの予定を検索をクリック

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能あありません

**Comment by shota-hope** [comment]
提出ありがとうございます。

- ジムの検索方法がわからなかったので、画面収録やスクショなどを使って教えてもらえますか？
  - [![Image from Gyazo](https://i.gyazo.com/86aa8998895fb395096a92fef102fdae.gif)](https://gyazo.com/86aa8998895fb395096a92fef102fdae) 
- ワークアウト予定を登録画面で、フォーム内容を埋めてない状態で送信するとエラーになりました。
- ユーザー画面で、新規登録時ににフォームを入力しないと、編集ができないようです（表示されないようです）
  - [![Image from Gyazo](https://i.gyazo.com/2d922e4f27154415d9f9d93303ba901c.png)](https://gyazo.com/2d922e4f27154415d9f9d93303ba901c)

ご確認よろしくお願いします。

**Comment by masuda456** [comment]
ご確認ありがとうございます。

１．ジムの検索方法
お送りいただいたキャプチャで使い方は合っているのですが、
たまに地図のロードが失敗する時があって、画面更新してもらえれば解決するのでそのメッセージを表示するようにしました。
一応、上手くいっている時のキャプチャを添付しておきます。

https://github.com/masuda456/runteq_graduate/assets/56382581/48a8b999-6d9b-4f8e-8ca6-47f5664b6c92


２．ワークアウト予定を登録画面で、フォーム内容を埋めてない状態で送信するとエラーになりました。
解消しました。
バリデーションメッセージを出すようにしたのとrequiredを追加しています。

３．ユーザー画面で、新規登録時ににフォームを入力しないと、編集ができないようです（表示されないようです）
失礼いたしました。
フラッシュメッセージの作業ブランチのマージ漏れのためでしたのでマージしてアップし直してメッセージが出ることを確認しております。


お手数ですが再度ご確認よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
https://github.com/masuda456/runteq_graduate/assets/61481161/f7e0d9d0-30c2-48e6-9c6d-0c6abe82b7dd



サインアップを行うとエラー画面が出てしまって、サインアップできなかったのですが...ご確認いただけますでしょうか。

**Comment by masuda456** [comment]
大変申し訳ありません。
１回目の修正に影響範囲があり、そちらの対応漏れになります。
先ほど修正して私の方でも公開環境上でのユーザーの登録が完了できたことを確認済みです。

度々で申し訳ありませんが、
引き続きご確認のほど宜しくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
